server {
    listen 80;

    server_tokens off;  # hide nginx version

    location / {
        proxy_pass http://app_upstream;

        proxy_set_header Host ;
        proxy_set_header X-Real-IP ;

        proxy_hide_header X-Powered-By;
    }
}
