name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t bedru26/node-docker-app .
          docker push bedru26/node-docker-app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # install docker if not installed
            if ! command -v docker &> /dev/null
            then
              sudo apt update
              sudo apt install docker.io docker-compose -y
            fi

            # clone repo if not exists
            if [ ! -d "app" ]; then
              git clone https://github.com/Bedru-Mekiyu/first-CI-CD.git app
            fi

            cd app

            # pull latest code (nginx + compose)
            git pull origin main

            # create .env dynamically
            echo "PORT=3000" > .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

            # pull latest docker image
            docker pull bedru26/node-docker-app

            # restart containers
            sudo docker-compose down
            sudo docker-compose up -d
